# Generated by Django 5.0.3 on 2024-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_cartitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
