# Generated by Django 5.0.3 on 2024-03-26 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_order"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Order",
        ),
    ]
